version: '3.8'

services:

  external_client:
    image: alpine
    container_name: external_client
    command: tail -f /dev/null
    networks:
      - client_net

  internal_client:
    image: alpine
    container_name: internal_client
    command: tail -f /dev/null
    networks:
      - client_net

  wifi_client:
    image: alpine
    container_name: wifi_client
    command: tail -f /dev/null
    networks:
      - client_net

  gateway:
    build: ./gateway
    container_name: gateway
    privileged: true
    networks:
      - client_net
      - backend_net
    depends_on:
      - db
    volumes:
      - ./gateway/logs:/var/logs
      - /dev/kmsg:/dev/kmsg

  pdp:
    build: ./pdp
    container_name: pdp
    networks:
      - backend_net


  db:
    image: postgres:14
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: zerotrust
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend_net

volumes:
  db_data:
  splunk_data:

networks:
  client_net:
  backend_net:
