services:

  # client-internal su rete interna
  client_internal:
    build:
      context: ./client_internal
    container_name: client_internal
    volumes:
      - ./pdp/data/blacklist:/app/blacklist
    networks:
      internal-net:
        ipv4_address: 172.20.0.2
    tty: true
    sysctls:
      - net.ipv4.conf.all.accept_redirects=1
    cap_add:
      - NET_ADMIN
    command: tail -f /dev/null
  
  # client-external su rete esterna
  client_external:
    build:
      context: ./client_external
    container_name: client_external
    volumes:
      - ./pdp/data/blacklist:/app/blacklist
    networks:
      external-net:
        ipv4_address: 172.21.0.2
    tty: true
    sysctls:
      - net.ipv4.conf.all.accept_redirects=1
    cap_add:
      - NET_ADMIN
    command: tail -f /dev/null
  
  # client wifi su rete wifi
  client_wifi:
    build:
      context: ./client_wifi
    container_name: client_wifi
    volumes:
      - ./pdp/data/blacklist:/app/blacklist
    networks:
      wifi-net:
        ipv4_address: 172.22.0.2
    tty: true
    sysctls:
      - net.ipv4.conf.all.accept_redirects=1
    cap_add:
      - NET_ADMIN
    command: tail -f /dev/null
  
  # Snort + Squid + iptables. Smista richieste verso pep.
  gateway:
    build:
      context: ./gateway
    container_name: gateway
    volumes:
      - ./logs/squid:/var/log/squid
      - ./logs/snort:/var/log/snort
      - ./pdp/data/blacklist:/app/blacklist
    ports:
      - "3128:3128"
    networks:
      internal-net:
        ipv4_address: 172.20.0.3
      external-net:
        ipv4_address: 172.21.0.3
      wifi-net:
        ipv4_address: 172.22.0.3
      zt-gateway:
        ipv4_address: 172.24.0.2
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    tty: true
    command: ["/bin/bash", "-c", "/etc/init.d/squid start && tail -f /dev/null"]
  
  # Verifica politiche di accesso e chiama il PDP
  pep:
    build:
      context: ./pep
    container_name: pep
    env_file:
      - ./pep/.env
    ports:
      - "3100:3100"
    networks:
      zt-gateway:
        ipv4_address: 172.24.0.3
      zt-core:
        ipv4_address: 172.25.0.2
    volumes:
      - ./pep/users_db.json:/app/users_db.json
    depends_on:
      - pdp
  
  # Decide in base a policy (es. reputazione IP, orario, etc.)
  pdp:
    build:
      context: ./pdp
    container_name: pdp
    networks:
      zt-core:
        ipv4_address: 172.25.0.3
    cap_add:
      - NET_ADMIN
    volumes:
      - ./pdp/data/trust_db.json:/app/trust_db.json
      - ./pdp/data/blacklist:/app/data/blacklist
    env_file:
      - ./pdp/.env

  # Risorsa protetta
  db:
    image: postgres:latest
    container_name: db
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      zt-core:
        ipv4_address: 172.25.0.4
    ports:
      - "5432:5432"
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./db/data.sql:/docker-entrypoint-initdb.d/02_data.sql
      - ./db/certs:/certs:ro
      - ./db/init/03_ssl.sh:/docker-entrypoint-initdb.d/03_ssl.sh:ro
      - db_data:/var/lib/postgresql/data

  splunk:
    image: splunk/splunk:latest
    container_name: splunk
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=${SPLUNK_PASSWORD}
    ports:
      - "8000:8000"
      - "8088:8088"
      - "8089:8089"
    networks:
      zt-core:
        ipv4_address: 172.25.0.5
    volumes:
      - ./logs/squid:/var/log/squid
      - ./logs/snort:/var/log/snort
      - ./splunk-apps/log_inputs:/opt/splunk/etc/apps/log_inputs
      - ./splunk-apps/dashboard:/opt/splunk/etc/apps/dashboard
      - ./splunk-apps/lookups:/opt/splunk/etc/apps/search/lookups
      - splunk_etc:/opt/splunk/etc
      - splunk_var:/opt/splunk/var

networks:
  internal-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
  external-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
  wifi-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16
  zt-gateway:
    driver: bridge
    ipam:
      config:
        - subnet: 172.24.0.0/16
  zt-core:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16

volumes:
  db_data:
  splunk_etc:
  splunk_var: