# docker-compose.yml
version: '3.8'

services:

  client-internal:
    image: ubuntu
    container_name: client-internal
    networks:
      internal-net:
        ipv4_address: 192.168.10.10
    tty: true
    command: bash

  client-external:
    image: ubuntu
    container_name: client-external
    networks:
      external-net:
        ipv4_address: 192.168.20.10
    tty: true
    command: bash

  client-wifi:
    image: ubuntu
    container_name: client-wifi
    networks:
      wifi-lan:
        ipv4_address: 192.168.30.10
    tty: true
    command: bash

  router:
    build: ./router
    container_name: router
    privileged: true                      # permette ip_forward e iptables
    sysctls:
      net.ipv4.ip_forward: 1             # abilitazione forwarding
    networks:
      internal-net:
        ipv4_address: 192.168.10.254
      external-net:
        ipv4_address: 192.168.20.254
      wifi-lan:
        ipv4_address: 192.168.30.254
      net-lab:
        ipv4_address: 192.168.200.254
    cap_add:
      - NET_ADMIN
    tty: true
    volumes:
      - ./logs/router:/var/log/router
      - ./logs/squid:/var/log/squid

networks:
  internal-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24
  external-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.20.0/24
  wifi-lan:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.30.0/24
  net-lab:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.200.0/24