version: '3.8'

services:

  external_client:
    image: ubuntu:22.04
    container_name: external_client
    command: tail -f /dev/null
    networks:
      client_net:
        ipv4_address: 172.18.0.2

  internal_client:
    image: ubuntu:22.04
    container_name: internal_client
    command: tail -f /dev/null
    networks:
      client_net:
        ipv4_address: 172.18.0.3

  gateway:
    build:
      context: ./gateway        # cartella dove risiede Dockerfile e squid/
      dockerfile: Dockerfile
    container_name: gateway
    cap_add:
      - NET_ADMIN              # serve per leggere/applicare iptables
    networks:
      client_net:
        ipv4_address: 172.18.0.4
      backend_net:
        ipv4_address: 172.19.0.4
    depends_on:
      - db
    volumes:
      - ./logs/squid:/var/log/squid

  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: zerotrust
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend_net

volumes:
  db_data:

networks:
  client_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16

  backend_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
