version: "3.8"

services:
  gateway:
    image: ubuntu:latest
    container_name: gateway
    build:
      context: ./gateway
    volumes:
      - ./gateway/squid.conf:/etc/squid/squid.conf
      - ./logs/squid:/var/log/squid
    ports:
      - "3128:3128"
    networks:
      zero_trust_net:
        ipv4_address: 172.18.0.2
    command: ["/bin/bash", "-c", "/etc/squid/squid.conf && tail -f /dev/null"]

  pep:
    build:
      context: ./pep
    container_name: pep
    networks:
      zero_trust_net:
        ipv4_address: 172.18.0.3
    depends_on:
      - pdp

  pdp:
    build:
      context: ./pdp
    container_name: pdp
    networks:
      zero_trust_net:
        ipv4_address: 172.18.0.4

  internal_client:
    image: curlimages/curl
    container_name: internal_client
    networks:
      zero_trust_net:
        ipv4_address: 172.18.0.5
    command: tail -f /dev/null

  external_client:
    image: curlimages/curl
    container_name: external_client
    networks:
      zero_trust_net:
        ipv4_address: 172.18.0.6
    command: tail -f /dev/null

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    networks:
      zero_trust_net:
        ipv4_address: 172.18.0.7
    ports:
      - "5432:5432"

networks:
  zero_trust_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
