FROM splunk/splunk:latest

# USER root

# COPY my_custom_alerts /opt/splunk/etc/apps/my_custom_alerts

# RUN microdnf update -y && \
#     microdnf install -y python3 python3-pip sudo && \
#     ln -s /usr/bin/python3 /usr/bin/python && \
#     python -m pip install --no-cache-dir requests pyyaml && \
#     chmod -R 755 /opt/splunk/etc/apps/my_custom_alerts && \
#     chmod +x /opt/splunk/etc/apps/my_custom_alerts/bin/policy_enforcer.py && \
#     # ✅ Permessi a tutta la struttura Splunk
#     chown -R splunk:splunk /opt/splunk && \
#     microdnf clean all

# # ❗ NON cambiare USER qui, Splunk gestisce tutto correttamente in entrypoint






